/**:
  ros__parameters:
    media_driver:
      srv_set_volume_name: "/robohead/media_driver/set_volume"
      srv_get_volume_name: "/robohead/media_driver/get_volume"
      srv_play_media_name: "/robohead/media_driver/play_media"
      topic_stream_name: "/robohead/media_driver/stream"
      stop_command: "__STOP__"
    
    ears_driver:
      srv_ears_set_angle_name: "/robohead/ears_driver/ears_set_angle"

    neck_driver:
      srv_neck_set_angle_name: "/robohead/neck_driver/neck_set_angle"
    
    respeaker_driver:
      topic_name:
        audio_main: "/robohead/respeaker_driver/audio/main"
        audio_channel_0: "/robohead/respeaker_driver/audio/channel_0"
        audio_channel_1: "/robohead/respeaker_driver/audio/channel_1"
        audio_channel_2: "/robohead/respeaker_driver/audio/channel_2"
        audio_channel_3: "/robohead/respeaker_driver/audio/channel_3"
        audio_channel_4: "/robohead/respeaker_driver/audio/channel_4"
        audio_channel_5: "/robohead/respeaker_driver/audio/channel_5"
        doa: "/robohead/respeaker_driver/doa"
        set_color_manual: "/robohead/respeaker_driver/set_color_manual"
      service_name:
        set_brightness: "/robohead/respeaker_driver/set_brightness"
        set_color_all: "/robohead/respeaker_driver/set_color_all"
        set_color_palette: "/robohead/respeaker_driver/set_color_palette"
        set_mode: "/robohead/respeaker_driver/set_mode"
    
    sensor_driver:
      topic_name: "/robohead/sensor_driver/battery"
    
    speech_recognizer_asr:
      service_name:
        set_mode: '/robohead/speech_recognizer/asr/set_mode'
      topic_name:
        commands: '/robohead/speech_recognizer/asr/commands'

    speech_recognizer_kws:
      service_name:
        set_mode: '/robohead/speech_recognizer/kws/set_mode'
      topic_name:
        wake_phrases: '/robohead/speech_recognizer/kws/wake_phrases'
        fast_commands: '/robohead/speech_recognizer/kws/fast_commands'
    
    usb_cam:
      topic_name_image_raw: "/robohead/usb_cam/image_raw"

    low_voltage_threshold: 6.3
    low_voltage_hysteresis: 0.5
    wait_timeout: 1.0

    actions_match: >


      {
        "std_wait": "/home/pi/robohead_ws/src/robohead2/robohead_controller/actions/std_wait/action.py",
        "std_low_bat": "/home/pi/robohead_ws/src/robohead2/robohead_controller/actions/std_low_bat/action.py",
        "слушай робот": "/home/pi/robohead_ws/src/robohead2/robohead_controller/actions/std_attention/action.py",
        "поздоровайся": "/home/pi/robohead_ws/src/robohead2/robohead_controller/actions/std_greeting/action.py",
        "покажи уши": "/home/pi/robohead_ws/src/robohead2/robohead_controller/actions/std_ears/action.py",
        "следи за шариком" : "/home/pi/robohead_ws/src/robohead2/robohead_controller/actions/std_ball_tracker/action.py",
        "сделай фото" : "/home/pi/robohead_ws/src/robohead2/robohead_controller/actions/std_make_photo/action.py",
        "покажи левое ухо" : "/home/pi/robohead_ws/src/robohead2/robohead_controller/actions/std_left_ear/action.py",
        "покажи правое ухо" : "/home/pi/robohead_ws/src/robohead2/robohead_controller/actions/std_right_ear/action.py"
      }
# {
#   "std_wait": "std_wait.action",
#   "слушай робот": "std_attention.action"
# }
# {
#   "wait_action": "std_wait.action",
#   "low_bat_action": "std_low_bat.action",
#   "слушайробот": "std_attention.action",
#   "покажи левое ухо": "std_left_ear.action",
#   "покажи правое ухо": "std_right_ear.action",
#   "покажи уши": "std_ears.action",
#   "сделай фото": "std_make_photo.action",
#   "поздоровайся": "std_greeting.action",
#   "следи за шариком": "std_ball_tracker.action",
#   "покажи напряжение": "std_voltage.action"
# }