/**:
  ros__parameters:
    timeout: 8.0
    default_mode: 0
    # 0 off recognition
    # 1 commands recognition
    # 2 free recognition
    sample_rate: 16000
    model_path: 'vosk-model-small-ru-0.22'
    timeout_text: '__TIMEOUT__'

    commands:
      - 'покажи уши'
      - 'покажи левое ухо'
      - 'покажи правое ухо'
      - 'поздоровайся'
      - 'сделай фото'

    ros:
      service_name:
        set_mode: 'set_mode'
      topic_name:
        commands: 'commands'
        audio_input: '/robohead/respeaker_driver/audio/main'
