/**:
  ros__parameters:
    grammar_timeout: 4.0
    default_mode: 3
    # 0 off recognition
    # 1 key words recognition
    # 2 commands recognition
    # 3 free recognition
    sample_rate: 16000
    model_path: 'vosk-model-small-ru-0.22'
    timeout_text: '__TIMEOUT__'
    wake_phrases:
      - "слушай робот"

    commands:
      - 'включи свет'
      - 'остановись'
      - 'вперёд'

    ros:
      service_name:
        set_mode: 'set_mode'
      topic_name:
        wake_phrases: 'wake_phrases'
        commands: 'commands'
        audio_input: '/respeaker_driver/audio/main'
