/**:
  ros__parameters:
    t_start_max: 5.0 # Начали распознавание и ждём это количество сек, чтоб принять решение что тишина
    t_end: 0.5 # Кол-во секунд после последнего слова, после которого считаем что фраза окончена
    t_max: 6.0 # Максимальная длительность одной фразы
    default_mode: 0
    # 0 off recognition
    # 1 commands recognition
    # 2 free recognition
    sample_rate: 16000
    model_path: 'vosk-model-small-ru-0.22'
    timeout_text: '__TIMEOUT__'

    commands:
      - 'покажи уши'
      - 'поздоровайся'

    ros:
      service_name:
        set_mode: 'set_mode'
      topic_name:
        commands: 'commands'
        audio_input: '/respeaker_driver/audio/main'
