<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>respeaker_driver</name>
  <version>2.0.0</version>
  <description>Package for get audio from respeaker usb mic array and control it.</description>
  <maintainer email="kolesnikovpi2005@mail.ru">kolezo-pi</maintainer>
  <author email="kolesnikovpi2005@mail.ru">kolezo-pi</author>
  <license>TODO</license>

  
  <depend>robohead_interfaces</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
