/**:
  ros__parameters:
    topic_name: "battery" # Название топика, куда публикуются данные с INA219
    publish_rate: 5 # Частота публикации в топик
    i2c_address: 67  # 0x43 in decimal, адрес INA219 на шине I2C в десятичном формате!
    i2c_bus: 1 # Номер шины i2C